config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :activity_logs do
    resources :thought_records

    collection do
      post 'update_many'
    end
  end

  get 'thought_records' => 'thought_records#index'

  root 'pages#index'

end

app/models/thought_record.rb
class ThoughtRecord < ActiveRecord::Base
  # Validations
  validates :CurrentSituation, presence: true
  validates :Outcome, presence: true
  validates :Emotions, presence: true
  validates :AutoThoughts, presence: true
  validates :AltResponse, presence: true
  validates :ActivityLog, presence: true

  # Associations
  belongs_to :ActivityLog, foreign_key: "activity_log_id"

end

app/controllers/thought_records_controller.rb
class ThoughtRecordsController < ApplicationController
  before_action :set_thought_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /thought_records
  # GET /thought_records.json
  # GET /activity_logs/:activity_log_id/thought_records
  # GET /activity_logs/:activity_log_id/thought_records.json
  def index
    # Render all if not viewed in the context of a activity log.
    if !params[:activity_log_id]
      @thought_records = []
      ActivityLog.where(User: current_user).each do |log|
        @thought_records << log.ThoughtRecord if log.ThoughtRecord
      end

    # Otherwise, render just associated with activity log
    else
      protect_log_created_by(params[:activity_log_id])
      @thought_records = ThoughtRecord.where(ActivityLog: params[:activity_log_id])
      @log = params[:activity_log_id]
    end
  end

  # GET /activity_logs/:activity_log_id/thought_records/1
  # GET /activity_logs/:activity_log_id/thought_records/1.json
  def show
    protect_log_created_by(params[:activity_log_id])
    protect_thought_created_by(params[:id])
  end

  # GET /activity_logs/:activity_log_id/thought_records/new
  def new
    @thought_record = ThoughtRecord.new
    @thought_record.ActivityLog = ActivityLog.find(params[:activity_log_id])
  end

  # GET /activity_logs/:activity_log_id/thought_records/1/edit
  def edit
    protect_log_created_by(params[:activity_log_id])
    protect_thought_created_by(params[:id])
  end

  # POST /activity_logs/:activity_log_id/thought_records
  # POST /activity_logs/:activity_log_id/thought_records.json
  def create
    @thought_record = ThoughtRecord.new(thought_record_params)
    @thought_record.ActivityLog = ActivityLog.find(params[:activity_log_id])
    # TODO: Make sure create only as part of activity log

    respond_to do |format|
      if @thought_record.save
        format.html { redirect_to [@thought_record.ActivityLog, @thought_record], notice: 'Thought record was successfully created.' }
        format.json { render :show, status: :created, location: @thought_record }
      else
        format.html { render :new }
        format.json { render json: @thought_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_logs/:activity_log_id/thought_records/1
  # PATCH/PUT /activity_logs/:activity_log_id/thought_records/1.json
  def update
    protect_log_created_by(params[:activity_log_id])
    protect_thought_created_by(params[:id])

    respond_to do |format|
      if @thought_record.update(thought_record_params)
        format.html { redirect_to [@thought_record.ActivityLog, @thought_record], notice: 'Thought record was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought_record }
      else
        format.html { render :edit }
        format.json { render json: @thought_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_logs/:activity_log_id/thought_records/1
  # DELETE /activity_logs/:activity_log_id/thought_records/1.json
  def destroy
    protect_log_created_by(params[:activity_log_id])
    protect_thought_created_by(params[:id])

    log = @thought_record.ActivityLog

    @thought_record.destroy
    respond_to do |format|
      format.html { redirect_to activity_log_thought_records_url(log), notice: 'Thought record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought_record
      @thought_record = ThoughtRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thought_record_params
      params.require(:thought_record).permit(:CurrentSituation, :Emotions, :Outcome, :AutoThoughts, :AltResponse)
    end
end

app/helpers/thought_records_helper.rb
module ThoughtRecordsHelper
end

app/views/thought_records/_form.html.erb
<%= form_for(@thought_record, url: url) do |f| %>
  <% if @thought_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought_record.errors.count, "error") %> prohibited this thought_record from being saved:</h2>

      <ul>
      <% @thought_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <strong>Current Situation</strong><br>
      <%= f.text_area :CurrentSituation,
      :placeholder => "Where were you and what was going on when you got upset?"%>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <strong>Emotions</strong><br>
      <%= f.text_area :Emotions,
      :placeholder => "What emotions (sad, anxious, angry, etc) did you feel at the time? Rate the intensity of each (0-100%)"%>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <strong>Automatic Thoughts</strong>
      <%= f.text_area :AutoThoughts,
      :placeholder => "What thoughts and/or images went through your mind? Rate your belief in each (0-100%)" %>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <strong>Alternative Responses</strong>
      <%= f.text_area :AltResponse,
      :placeholder => "Use the questions below to compose responses to the automatic thoughts. Rate your belief in each (0-100%). Also, consult the list of possible distortions" %>
    </div>
  </div>
  <div class="row">
    <div class ="large-12 columns">
      1. What is the evidence that automatic thought is true? What is the evidence that it is not true?
    </div>
  </div>
  <div class="row">
    <div class ="large-12 columns">
      2. Are there alternative explanations for that event or alternative ways to view the situation?
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      3. What are the implications if the thought is true? What's the most upsetting thing about it? What's the most realistic view? What can I do about it?
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      4. What would I tell a good friend in the same situation?
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <u>Possible Distortions:</u> All-or-nothing Thinking; Overgeneralizing; Discounting the Postives; Jumping to conclusions; Mind-reading;
      Fortune-telling; Magnifying/Minimizing; Emotional Reasoning; Making "Should" Statements; Labeling; Inappropriate Blaming.
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <br><strong>Outcome</strong>
      <%= f.text_area :Outcome,
      :placeholder => "Rerate your belief in your automatic thoughts (0-100%) and in the intensity of your emotions (0-100%)" %>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/thought_records/edit.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Edit Thought Record</h1>
  </div>
</div>

<%= render partial: 'form', locals: {url: activity_log_thought_record_path(@thought_record.ActivityLog, @thought_record)} %>

<div class="row">
  <div class="large-12 columns">
    <%= link_to 'Back', activity_log_thought_records_path(@thought_record.ActivityLog) %>
  </div>
</div>

app/views/thought_records/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="large-12 columns">
    <% if user_signed_in? %>
      <h1><%= current_user.Name %>'s Thought Records</h1>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <table class="thought-table">
      <thead>
        <tr>
          <th class="date-time">Date - Time</th>
          <th class="situation">Situation</th>
          <th class="show-bar"></th>
        </tr>
      </thead>
      <tbody>
        <% @thought_records.reverse.each do |thought_record| %>
          <tr>
            <td><<%= thought_record.updated_at %></td>
            <td><%= thought_record.CurrentSituation %></td>
            <td><%= link_to 'Show', activity_log_thought_record_path(thought_record.ActivityLog, thought_record) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<% if params[:activity_log_id] && @thought_records.length > 0 %>
  <%= link_to 'New Thought record', new_activity_log_thought_record_path(@thought_records[0].ActivityLog) %>
<% end %>

app/views/thought_records/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>New Thought Record</h1>
  </div>
</div>

<%= render partial: 'form', locals: {url: activity_log_thought_records_path(@thought_record.ActivityLog)} %>

<div class="row">
  <div class="large-12 columns">
    <%= link_to 'Back', thought_records_path %>
  </div>
</div>

app/views/thought_records/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="large-12 columns">
    <h1>Thought Record for <%= @thought_record.updated_at %></h1>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <table class="show-table">
      <tr>
        <td class="show-left-col">
          <strong>Current Situation</strong><br>
        </td>
        <td>
          <%= @thought_record.CurrentSituation %>
        </td>
      </tr>
      <tr>
        <td class="show-left-col">
          <strong>Emotions</strong><br>
        </td>
        <td>
          <%= @thought_record.Emotions %>
        </td>
      </tr>
      <tr>
        <td class="show-left-col">
          <strong>Automatic Thoughts</strong><br>
        </td>
        <td>
          <%= @thought_record.AutoThoughts %>
        </td>
      </tr>
      <tr>
        <td class="show-left-col">
          <strong>Alternative Response</strong><br>
        </td>
        <td>
          <%= @thought_record.AltResponse %>
        </td>
      </tr>
      <tr>
        <td class="show-left-col">
          <strong>Outcome</strong><br>
        </td>
        <td>
          <%= @thought_record.Outcome %>
        </td>
      </tr>
    </table>
  </div>
</div>

<%= link_to 'Edit', edit_activity_log_thought_record_path(@thought_record.ActivityLog, @thought_record) %> |
<%= link_to 'Back', activity_log_thought_records_path(@thought_record.ActivityLog) %>