config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :activity_logs do
    resources :thought_records

    collection do
      post 'update_many'
    end
  end

  get 'thought_records' => 'thought_records#index'

  root 'pages#index'

end

app/models/activity_log.rb
class ActivityLog < ActiveRecord::Base
  # Validations
  validates :CurrentActivity, presence: true
  validates :CurrentMood, presence: true

  # Associations
  belongs_to :User
  has_one :ThoughtRecord
end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
  before_action :set_activity_log, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /activity_logs
  # GET /activity_logs.json
  def index
    @activity_logs = ActivityLog.where(User: current_user).order(:LogWindow)
  end

  # POST /activity_logs
  def update_many
    # loop over params
    errors = []
    for i in current_user.NormalWake..(current_user.NormalSleep + 12)
      if (!params["current_activity-" + i.to_s].blank? && !params["current_mood-" + i.to_s].blank?)

        # Update an existing record if there
        if (ActivityLog.where(User: current_user, LogWindow: i).exists?)
          puts "exists"
          log = ActivityLog.where(User: current_user, LogWindow: i).first
          log.CurrentActivity = params["current_activity-" + i.to_s]
          log.CurrentMood = params["current_mood-" + i.to_s]
        else
          puts "new"
          # TODO: Variable date
          log = ActivityLog.new(CurrentActivity: params["current_activity-" + i.to_s],
                  CurrentMood: params["current_mood-" + i.to_s],
                  LogWindow: i,
                  LogDate: Date.current().to_s(:iso8601),
                  User: current_user)
        end

        # Attempt to save the log
        if !log.save
          errors << "Could not update record for #{i}:00, please try again"
        end

      # Is one there but not the other? Let the user know
      elsif (!!params["current_activity-" + i.to_s].blank? ^ !!params["current_mood-" + i.to_s].blank?)
          errors << "Missing some data for #{i}:00, please try again."
      end
    end

    # TODO: Display the errors array
    redirect_to activity_logs_url, notice: 'Logs were updated.'
  end

  # GET /activity_logs/1
  # GET /activity_logs/1.json
  def show
    protect_log_created_by(params[:id])
  end

  # GET /activity_logs/new
  def new
    @activity_log = ActivityLog.new
  end

  # GET /activity_logs/1/edit
  def edit
    protect_log_created_by(params[:id])
  end

  # POST /activity_logs
  # POST /activity_logs.json
  def create
    @activity_log = ActivityLog.new(activity_log_params)
    @activity_log.User = current_user

    respond_to do |format|
      if @activity_log.save
        format.html { redirect_to @activity_log, notice: 'Activity log was successfully created.' }
        format.json { render :show, status: :created, location: @activity_log }
      else
        format.html { render :new }
        format.json { render json: @activity_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_logs/1
  # PATCH/PUT /activity_logs/1.json
  def update
    protect_log_created_by(params[:id])

    respond_to do |format|
      if @activity_log.update(activity_log_params)
        format.html { redirect_to @activity_log, notice: 'Activity log was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_log }
      else
        format.html { render :edit }
        format.json { render json: @activity_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_logs/1
  # DELETE /activity_logs/1.json
  def destroy
    protect_log_created_by(params[:id])

    @activity_log.destroy
    respond_to do |format|
      format.html { redirect_to activity_logs_url, notice: 'Activity log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_log
      @activity_log = ActivityLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_log_params
      if (params[:activity_log])
        params.require(:activity_log).permit(:CurrentActivity, :CurrentMood)
      end
      # TODO: Strong params on many update case
    end
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
  def windowify(myint)
    return "#{myint}:00 - #{myint+1}:00"
  end
end

app/views/activity_logs/_form.html.erb
<%= form_for(@activity_log) do |f| %>
  <% if @activity_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_log.errors.count, "error") %> prohibited this activity_log from being saved:</h2>

      <ul>
      <% @activity_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :current_activity %><br>
    <%= f.text_area :CurrentActivity %>
  </div>
  <div class="field">
    <%= f.label :current_mood %><br>
    <%= f.number_field :CurrentMood %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_logs/edit.html.erb
<h1>Editing Activity Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_log %> |
<%= link_to 'Back', activity_logs_path %>

app/views/activity_logs/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
  <h1><%= current_user.Name %>'s Activity Logs</h1>
<% end %>

<%= form_tag(update_many_activity_logs_path, method: "post") do |f| %>
<% if ActivityLog.where(:LogDate => 2.days.ago.strftime("%Y-%m-%d")).exists? %>
<%  %>
 <table class='show-for-large-up'>
   <caption>2 days ago</caption>
   <thead>
     <tr>
       <th>Log Window</th>
       <th>Activity</th>
       <th>Mood Rating</th>
       <th>Thought Record?</th>
     </tr>
   </thead>
 </table>
 <% end %>

 <% if ActivityLog.where(:LogDate => 1.days.ago.strftime("%Y-%m-%d")).exists? %>
 <%  %>
  <table class='show-for-medium-up'>
    <caption>Yesterday</caption>
    <thead>
      <tr>
        <th>Log Window</th>
        <th>Activity</th>
        <th>Mood Rating</th>
        <th>Thought Record?</th>
      </tr>
    </thead>
  </table>
  <% end %>

  <table class='show-for-small-up'>
    <caption><%= Date.today.to_s %></caption>
    <thead>
      <tr>
        <th>Log Window</th>
        <th>Activity</th>
        <th>Mood Rating</th>
        <th>Thought Record?</th>
      </tr>
    </thead>

    <tbody>
      <% i = 0 %>
      <% @activity_logs.where(:LogDate => Date.today.to_s).each do |a_log| %>
        <% i +=1 %>
        <tr>
          <td><%= windowify(a_log.LogWindow) %></td>
          <td><%= a_log.CurrentActivity %></td>
          <td><%= a_log.CurrentMood %></td>
          <td>
            <% if ThoughtRecord.where(:ActivityLog => a_log).exists? %>
                <%= link_to 'Show', activity_log_thought_record_path(a_log, ThoughtRecord.where(:ActivityLog => a_log).first) %>
            <% else %>
                <%= link_to 'New', new_activity_log_thought_record_path(a_log) %>
            <% end %>
          </td>
        </tr>

      <% end %>

      <% for j in (current_user.NormalWake + i)..(current_user.NormalSleep + 11) %>
          <tr>
            <td>
              <%= windowify(j) %>
            </td>
            <td><%= text_area_tag(("current_activity-" + j.to_s).to_sym) %></td>
            <td><%= number_field_tag(("current_mood-" + j.to_s).to_sym) %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
  <%= submit_tag("Save", :class =>"button round small")%>
<% end %>
<br>

app/views/activity_logs/new.html.erb
<h1>New Activity Log</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_logs_path %>

app/views/activity_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @activity_log.CurrentActivity %>
</p>

<p>
  <strong>Mood Rating:</strong>
  <%= @activity_log.CurrentMood %>
</p>

<%= link_to 'Edit', edit_activity_log_path(@activity_log) %> |
<%= link_to 'Back', activity_logs_path %>