config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :activity_logs do
    resources :thought_records

    collection do
      post 'update_many'
    end
  end

  get 'thought_records' => 'thought_records#index'

  root 'pages#index'

end

app/views/layouts/_header_nav.html.erb
<aside class="left-off-canvas-menu hide-for-medium-up">
  <ul class="off-canvas-list">
    <li><label>Ocelot</label></li>
    <li> <%= link_to 'Activity Log', activity_logs_path %></li>
    <li> <%= link_to 'Thought Records', thought_records_path if true %></li>
    <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>

  </ul>
</aside>


<nav class="tab-bar hide-for-medium-up">
  <section class="left-small">
    <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
  </section>

  <section class="middle tab-bar-section">
    <h1 class="title">Ocelot</h1>
  </section>
</nav>

<nav class="top-bar hide-for-small-only">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#"></a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li> <%= link_to 'Activity Log', activity_logs_path %></li>
      <li> <%= link_to 'Thought Records', thought_records_path %></li>
      <% if user_signed_in? %>
      <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li> <%= link_to 'Sign In', users_path %></li>
      <% end %>
    </ul>
    <ul class="right">
        <li> <%= link_to 'Ocelot', users_path %></li>
    </ul>

  </section>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Ocelot</title>


    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "scaffolds.scss" %>
    <%= stylesheet_link_tag    "thought_records.scss" %>
    <%= stylesheet_link_tag    "activity_logs.scss" %>
    <%= stylesheet_link_tag    "users.scss" %>
    <%= stylesheet_link_tag    "page" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">


    <%= render "layouts/header_nav" %>



    <section class="main-section">
      <div class="row frosty">
        <div class="large-12 columns">
          <%= yield %>
        </div>
      </div>
    </section>

  <a class="exit-off-canvas"></a>

  </div>
</div>

  </body>
</html>